default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: nfe_handler_maino_development

test:
  <<: *default
  database: nfe_handler_maino_test

production:
  <<: *default
  database: <%= ENV["APPSETTING_DB_NAME"] %>
  username: <%= ENV["APPSETTING_DB_USER"] %>
  password: <%= ENV["APPSETTING_DB_PASSWORD"] %>
  host: <%= ENV["APPSETTING_DB_HOST"] %>
  port: <%= ENV["APPSETTING_DB_PORT"] %>
