# frozen_string_literal: true

# == Schema Information
#
# Table name: invoice_item_totals
#
#  id              :bigint           not null, primary key
#  vICMS           :decimal(15, 2)   default(0.0), not null
#  vIPI            :decimal(15, 2)   default(0.0), not null
#  vII             :decimal(15, 2)   default(0.0), not null
#  vIOF            :decimal(15, 2)   default(0.0), not null
#  vTotTrib        :decimal(15, 2)   default(0.0), not null
#  invoice_item_id :bigint           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class InvoiceItemTotal < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :invoice_item

  # @validations ..............................................................
  validates :vICMS, :vIPI, :vII, :vIOF, :vTotTrib, numericality: true, allow_nil: true

  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end
