# frozen_string_literal: true

# == Schema Information
#
# Table name: invoice_batches
#
#  id         :bigint           not null, primary key
#  invoice_id :bigint           not null
#  batch_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class InvoiceBatch < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :invoice
  belongs_to :batch

  # @validations ..............................................................
  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end
